# Sidebar navigation

- label: "Pesiapan Awal"
  link: "/"

- label: Cek Saldo
  link: "/cek-saldo"

- label: Produk
  items:
    - label: "Kategori Produk"
      link: "/produk/kategori"
    - label: "Operator Produk"
      link: "/produk/operator"
    - label: "Jenis Produk"
      link: "/produk/jenis"
    - label: "Produk List"
      link: "/produk/list"

- label: Transaksi
  items:
    - label: "Metode POST"
      link: "/transaksi/post"
    - label: "Metode GET"
      link: "/transaksi/get"
    - label: "Metode GET HTTP Text"
      link: "/transaksi/get-text"

- label: Status Transaksi
  items:
    - label: "Metode POST"
      link: "/cek-status/post"
    - label: "Metode GET"
      link: "/cek-status/get"

- label: Lainnya
  items:
    - label: Simulasi API
      link: "https://documenter.getpostman.com/view/22544220/VUjPGPwm"
